#!/usr/bin/bash

export CFLAGS="-DSQLITE_THREADSAFE=0 \
-DSQLITE_DEFAULT_MEMSTATUS=0 \
-DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 \
-DSQLITE_LIKE_DOESNT_MATCH_BLOBS \
-DSQLITE_MAX_EXPR_DEPTH=0 \
-DSQLITE_OMIT_DECLTYPE \
-DSQLITE_OMIT_DEPRECATED \
-DSQLITE_OMIT_PROGRESS_CALLBACK \
-DSQLITE_OMIT_SHARED_CACHE \
-DSQLITE_USE_ALLOCA \
-DHAVE_FDATASYNC=1 \
-DHAVE_GMTIME_R=1 \
-DHAVE_ISNAN=1 \
-DHAVE_LOCALTIME_R=1 \
-DHAVE_LOCALTIME_S=1 \
-DHAVE_MALLOC_USABLE_SIZE=1 \
-DHAVE_STRCHRNUL=1 \
-DHAVE_USLEEP=1 \
-DHAVE_UTIME=1 \
-DSQLITE_BYTEORDER=1234 \
-DSQLITE_DEFAULT_CACHE_SIZE=16384 \
-DSQLITE_DEFAULT_FOREIGN_KEYS=1 \
-DSQLITE_DEFAULT_PAGE_SIZE=4096 \
-DSQLITE_TEMP_STORE=3 \
-DSQLITE_USE_URI=1 \
-DSQLITE_ENABLE_BATCH_ATOMIC_WRITE \
-DSQLITE_ENABLE_UPDATE_DELETE_LIMIT=1 \
-DSQLITE_CORE"

./configure
make sqlite3.c
